name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Download 32-bit artifacts
      - name: Download Windows Build Artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          name: Windows Build
          workflow: rust.yml
          branch: master
          path: ./artifacts/windows

      - name: Download Linux Build Artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          name: Linux Build
          workflow: rust.yml
          branch: master
          path: ./artifacts/linux

      # Download 64-bit artifacts
      - name: Download Windows x64 Build Artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          name: Windows Build x64
          workflow: rust.yml
          branch: master
          path: ./artifacts/windows-x64

      # - name: Download Linux x64 Build Artifact
      #   uses: dawidd6/action-download-artifact@v11
      #   with:
      #     name: Linux Build x64
      #     workflow: rust.yml
      #     branch: master
      #     path: ./artifacts/linux-x64

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: |
            ./artifacts/windows/i686-pc-windows-msvc/release/rustick.dll
            ./artifacts/windows/i686-pc-windows-msvc/release/rustick.pdb
            ./artifacts/windows-x64/x86_64-pc-windows-msvc/release/rustick64.dll
            ./artifacts/windows-x64/x86_64-pc-windows-msvc/release/rustick64.pdb
            ./artifacts/linux/i686-unknown-linux-gnu/release/librustick.so
            ./artifacts/linux/i686-unknown-linux-gnu/release/librustick.so.dbg
            ./artifacts/windows/rustick.dm

# ./artifacts/linux-x64/x86_64-unknown-linux-gnu/release/librustick64.so
# ./artifacts/linux-x64/x86_64-unknown-linux-gnu/release/librustick64.so.dbg
